### ISSUE TITLE
Cambiar disposicion del menu

### ISSUE THREAD

**Issue by sflorio** [sflorio/CarAgency#12]
el menú deberá tener la siguiente disposicion
>home
>Vehiculos
>>Lista deVehiculos
>>Ingreso de Vehiculos
>Configuracion
>>Marcas
>>Modelos
>>Estados Civiles
>><El resto de las entidades de las que dependen los vehiculos, personas y transacciones>

**Comment by jpalomino92** [comment]
listo,se modifico el nav y se agruparon los formularios.
